#!/bin/sh
# Probe the size and alignment of every public cgltf struct with the host C compiler and pin
# them on the C3 side.
#
# Usage:
#   scripts/probe-layout.sh            print the probed layouts
#   scripts/probe-layout.sh --check    fail if a layout drifted from scripts/abi-sizes.txt
#   scripts/probe-layout.sh --update   rewrite scripts/abi-sizes.txt and src/layout.c3
#
# The compiler is cc under a Linux shell and cl under a Windows one, so each CI job measures
# its own platform. scripts/abi-sizes.txt is shared by both targets: the layouts were measured
# identical, so --check on either platform gates the other's pins.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HEADER="$ROOT/vendor/cgltf/cgltf.h"
SIZES="$ROOT/scripts/abi-sizes.txt"
LAYOUT="$ROOT/src/layout.c3"
MODE="${1:-}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# One line per struct: the C name and its C3 spelling.
TYPES='
cgltf_memory_options MemoryOptions
cgltf_file_options FileOptions
cgltf_options Options
cgltf_extras Extras
cgltf_extension Extension
cgltf_buffer Buffer
cgltf_meshopt_compression MeshoptCompression
cgltf_buffer_view BufferView
cgltf_accessor_sparse AccessorSparse
cgltf_accessor Accessor
cgltf_attribute Attribute
cgltf_image Image
cgltf_sampler Sampler
cgltf_texture Texture
cgltf_texture_transform TextureTransform
cgltf_texture_view TextureView
cgltf_pbr_metallic_roughness PbrMetallicRoughness
cgltf_pbr_specular_glossiness PbrSpecularGlossiness
cgltf_clearcoat Clearcoat
cgltf_transmission Transmission
cgltf_ior Ior
cgltf_specular Specular
cgltf_volume Volume
cgltf_sheen Sheen
cgltf_emissive_strength EmissiveStrength
cgltf_iridescence Iridescence
cgltf_diffuse_transmission DiffuseTransmission
cgltf_anisotropy Anisotropy
cgltf_dispersion Dispersion
cgltf_material Material
cgltf_material_mapping MaterialMapping
cgltf_morph_target MorphTarget
cgltf_draco_mesh_compression DracoMeshCompression
cgltf_mesh_gpu_instancing MeshGpuInstancing
cgltf_primitive Primitive
cgltf_mesh Mesh
cgltf_skin Skin
cgltf_camera_perspective CameraPerspective
cgltf_camera_orthographic CameraOrthographic
cgltf_camera Camera
cgltf_light Light
cgltf_node Node
cgltf_scene Scene
cgltf_animation_sampler AnimationSampler
cgltf_animation_channel AnimationChannel
cgltf_animation Animation
cgltf_material_variant MaterialVariant
cgltf_asset Asset
cgltf_data Data
'

if [ ! -f "$HEADER" ]; then
    echo "ERROR: vendor/cgltf is empty. Run: git submodule update --init" >&2
    exit 1
fi

{
    echo '#include <stdio.h>'
    echo '#include <stddef.h>'
    echo "#include \"$HEADER\""
    echo 'int main(void) {'
    printf '%s\n' "$TYPES" | while read -r cname c3name; do
        [ -z "$cname" ] && continue
        printf '    printf("%s %%zu %%zu\\n", sizeof(%s), _Alignof(%s));\n' "$cname" "$cname" "$cname"
    done
    echo '    return 0;'
    echo '}'
} > "$WORK/probe.c"

case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        (cd "$WORK" && cl /nologo /std:c11 /Fe:probe.exe probe.c > /dev/null)
        PROBE="$WORK/probe.exe"
        ;;
    *)
        cc -std=c11 -o "$WORK/probe" "$WORK/probe.c"
        PROBE="$WORK/probe"
        ;;
esac

"$PROBE" > "$WORK/sizes.txt"

generate_layout() {
    echo 'module gltf;'
    echo ''
    echo '// Generated by scripts/probe-layout.sh from scripts/abi-sizes.txt. Do not edit.'
    echo ''
    printf '%s\n' "$TYPES" | while read -r cname c3name; do
        [ -z "$cname" ] && continue
        line="$(grep "^$cname " "$WORK/sizes.txt")"
        size="$(printf '%s' "$line" | cut -d' ' -f2)"
        align="$(printf '%s' "$line" | cut -d' ' -f3)"
        echo "\$assert $c3name::size == $size;"
        echo "\$assert $c3name::alignment == $align;"
    done
}

case "$MODE" in
    --update)
        cp "$WORK/sizes.txt" "$SIZES"
        generate_layout > "$LAYOUT"
        echo "wrote $SIZES and $LAYOUT"
        ;;
    --check)
        if ! diff -u "$SIZES" "$WORK/sizes.txt"; then
            echo "ERROR: probed layout differs from scripts/abi-sizes.txt" >&2
            exit 1
        fi
        generate_layout > "$WORK/layout.c3"
        if ! diff -u "$LAYOUT" "$WORK/layout.c3"; then
            echo "ERROR: src/layout.c3 is stale; run scripts/probe-layout.sh --update" >&2
            exit 1
        fi
        echo "layout pins match"
        ;;
    *)
        cat "$WORK/sizes.txt"
        ;;
esac
